### ISSUE TITLE
"Show output segments in 3D" takes very long

### ISSUE THREAD

**Issue by rbumm** [rbumm/SlicerLungCTAnalyzer#16]
... during the first run.

**Comment by lassoan** [comment]
It is due to having tens of millions of tiny surface segments because of the noisy voxel values and small details in the image. Probably the time could be reduced by 1-2 magnitudes if we apply smoothing (it consolidates few-voxel fragments into larger blobs). If you don't want to smooth then you can use volume rendering to visualize the results, similarly to the preview. You can adjust gradient opacity transfer function or maximum opacity projection mode, or set ventilated regions opacity to very low to ensure make dense regions show up well, from any viewpoint.

What is the goal of the 3D visualization? What do you need to see?

**Comment by rbumm** [comment]
Thanks for the explanation, I recently calculated the number of voxels myself and the numbers get breathtakingly high even in 
such a "small" 512 x 512 x 512 resolution. 

> What is the goal of the 3D visualization? What do you need to see?

The leading feature in Lung Analyzer should be reliable volume calculation for individual compartments. The 3D effect is a bit of overkill right now if all segments are displayed together, maybe it already helps if one reduces the number of visual segments. We see a lot of dorsal lung infiltrations in severe ARDS or COVID cases and our ICU doctors turn ventilated patients (prone) to counteract hydrostatic effects. 3D may help to better visualize the fluid-filled areas and demonstrate treatment effects.  I will experiment on that display a bit and discuss it with the team ...

**Comment by lassoan** [comment]
We can have a quick interactive session with screen sharing so that I can show you what options are available. Give me a few timeslots that would work for you this week.

**Comment by rbumm** [comment]
That would great, I would be available best tomorrow, Tuesday 15th (15:00-20:00 UTC) or Friday 18th (13:00-16:00 UTC) ...

**Comment by lassoan** [comment]
Today (Tuesday) we give presentations at the [Slicer project week](https://projectweek.na-mic.org/PW34_2020_Virtual/), so unfortunately I'm not available, but Friday 15:00 UTC works well.

**Comment by rbumm** [comment]
Ok, confirmed ! Zoom ? Glad if you could DM me the details. I was not aware of the project week, very interesting, tried to register right now and hope to get a Zoom link.
