### ISSUE TITLE
Exception upon repeated "Compute results"

### ISSUE THREAD

**Issue by rbumm** [rbumm/SlicerLungCTAnalyzer#18]
**Failed to compute results: expects 0 \<= id && id \< GetNumberOfValues()**

is thrown in createResultTable function when repeated computations with different thresholds are made.

@lassoan any suggestions ? 

![](https://user-images.githubusercontent.com/18140094/105577778-f2c09500-5d7b-11eb-9584-0cb94bbfa6f3.png)

**Comment by lassoan** [comment]
This is probably because of `rowIndex` is out of range (not enough rows in minThrCol, probably because not enough rows in  self.resultsTable). If you [set up a debugger](https://www.slicer.org/wiki/Documentation/Nightly/Extensions/DebuggingTools#Tutorials) and put a breakpoint there then it should not be hard to figure out what goes wrong.

**Comment by rbumm** [comment]
Problem will be monitored and possibly debugged. 

My first guess is that I used thresholds that did not result in pruduction valid segments, so not enough rows were present for display in the table.
