### ISSUE TITLE
Cannot select a volume in Input lung CT manual

### ISSUE THREAD

**Issue by zh-zhang1984** [rbumm/SlicerLungCTAnalyzer#31]
Dear auhtors,
Thank you for your excellent package for processing lung image; However, when I loaded a series of lung CT in .tiff format, I follow the instruction for "Lung CT Analyzer". I found I cannot select a volume (i.e. when I click on the tool bar, there is no dropdown list). Can you give me some hints to solve this problem?

**Comment by rbumm** [comment]
Tiff is not a suitable format to retain image geometry. Make sure to save your Tiff volume as nrrd file or better load the data as DICOM files so that you should be able to see the CT volume in the dropdown list. If you run into problems, probably it would be good to ask this question again in the [3D Slicer discourse](https://discourse.slicer.org/).  I am closing this issue here.

**Comment by lassoan** [comment]
TIFF images are probably loaded as color images. You can convert them to scalar volume using `Vector to scalar volume` module, but I agree with @rbumm that such images should not be used for any image analysis, because it is hard to guarantee that image geometry and quality (e.g., bit depth, value range) are preserved.
